### ISSUE TITLE
Toaster props are not optional

### ISSUE THREAD

**Issue by BearToCode** [devloop01/sonner-svelte#38]
Hello, I'm just checking out the library and it seems that the `<Toaster />` component requires all the props to be provided, even thought they should all be optional. This is what the generated `toaster.svelte.d.ts` definiton file looks like:

```ts
import { SvelteComponent } from "svelte";
import type { Component, Direction, Theme, ToastOptions, ToastPosition } from '../internal/types.js';
interface ToasterProps {
    position: ToastPosition;
    // ...
}
import './style.css';
declare const __propDef: {
    props: {
        position?: ToastPosition | undefined;
        //...
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
type ToasterProps_ = typeof __propDef.props;
export { ToasterProps_ as ToasterProps };
export type ToasterEvents = typeof __propDef.events;
export type ToasterSlots = typeof __propDef.slots;
export default class Toaster extends SvelteComponent<ToasterProps, ToasterEvents, ToasterSlots> {
}
```

As you can see the `ToasterProps` used in the declaration of the `SvelteComponent` is the one with all the properties being required.

**Comment by devloop01** [comment]
Thanks for pointing out gotta fix that! `Type`

**Comment by devloop01** [comment]
Hi @BearToCode, I looked into the issue and I can say that the `ToasterProps` is created like that because of some typescript weirdness in the code.
Yes, all the props are optional so it doesn't affect how you might use the library, it's all internal.

If I make all props of the type optional, the variable types are not inferred correctly.
Say, I make the `gap` prop optional in `ToasterProps` which I then use in the code like:
```ts
export let gap: ToasterProps['gap'] = GAP;
```
even though `gap` here has a fallback/default value, the type for `gap` still gets inferred as `number | undefined`, which creates other issues.

Also, if you check the final build, inside `toaster.d.ts` the props are optional.
```ts
declare const __propDef: {
    props: {
        position?: ToastPosition | undefined;
        hotkey?: string[] | undefined;
        expand?: boolean | undefined;
        // other types
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
```

I think the new version of Svelte will fix this issue but I will keep it way for now to avoid having a headache 😅
